# Generated by Django 4.2.7 on 2026-05-27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文档标题')),
                ('file', models.FileField(upload_to='requirement_docs/%Y/%m/', verbose_name='文档文件')),
                ('document_type', models.CharField(choices=[('pdf', 'PDF文档'), ('docx', 'Word文档'), ('txt', '文本文档'), ('md', 'Markdown文档'), ('png', 'PNG图片'), ('jpg', 'JPG图片'), ('jpeg', 'JPEG图片'), ('gif', 'GIF图片')], max_length=10, verbose_name='文档类型')),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('analyzing', '分析中'), ('analyzed', '分析完成'), ('failed', '分析失败')], default='uploaded', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='文件大小(bytes)')),
                ('extracted_text', models.TextField(blank=True, verbose_name='提取的文本内容')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_documents', to='projects.project', verbose_name='关联项目')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '需求文档',
                'verbose_name_plural': '需求文档',
                'db_table': 'requirement_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequirementAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_report', models.TextField(blank=True, verbose_name='分析报告')),
                ('requirements_count', models.PositiveIntegerField(default=0, verbose_name='需求数量')),
                ('analysis_time', models.FloatField(blank=True, null=True, verbose_name='分析耗时(秒)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='requirement_analysis.requirementdocument', verbose_name='关联文档')),
            ],
            options={
                'verbose_name': '需求分析',
                'verbose_name_plural': '需求分析',
                'db_table': 'requirement_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='需求知识图谱', max_length=100, verbose_name='图谱名称')),
                ('description', models.TextField(blank=True, verbose_name='图谱描述')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公共图谱')),
                ('public_access_level', models.CharField(choices=[('read', '只读'), ('write', '可编辑')], default='read', max_length=20, verbose_name='公共访问权限')),
                ('status', models.CharField(choices=[('pending', '待构建'), ('building', '正在构建'), ('completed', '构建完成'), ('failed', '构建失败')], default='pending', max_length=20, verbose_name='状态')),
                ('node_count', models.PositiveIntegerField(default=0, verbose_name='实体节点数')),
                ('edge_count', models.PositiveIntegerField(default=0, verbose_name='关系边数')),
                ('document_count', models.PositiveIntegerField(default=0, verbose_name='文档数')),
                ('build_started_at', models.DateTimeField(blank=True, null=True, verbose_name='构建开始时间')),
                ('build_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='构建完成时间')),
                ('build_error_message', models.TextField(blank=True, verbose_name='构建错误信息')),
                ('working_dir', models.CharField(blank=True, max_length=500, verbose_name='工作目录')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('documents', models.ManyToManyField(related_name='knowledge_graphs', to='requirement_analysis.requirementdocument', verbose_name='关联文档')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_graphs', to='projects.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '知识图谱',
                'verbose_name_plural': '知识图谱',
                'db_table': 'knowledge_graphs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGraphVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=20, verbose_name='版本号')),
                ('version_name', models.CharField(blank=True, max_length=100, verbose_name='版本名称')),
                ('description', models.TextField(blank=True, verbose_name='版本描述')),
                ('snapshot_data', models.JSONField(default=dict, verbose_name='快照数据')),
                ('node_count', models.PositiveIntegerField(default=0, verbose_name='实体节点数')),
                ('edge_count', models.PositiveIntegerField(default=0, verbose_name='关系边数')),
                ('document_count', models.PositiveIntegerField(default=0, verbose_name='文档数')),
                ('document_ids', models.JSONField(default=list, verbose_name='关联文档ID列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='requirement_analysis.knowledgegraph', verbose_name='关联图谱')),
            ],
            options={
                'verbose_name': '知识图谱版本',
                'verbose_name_plural': '知识图谱版本',
                'db_table': 'knowledge_graph_versions',
                'ordering': ['-created_at'],
                'unique_together': {('graph', 'version_number')},
            },
        ),
    ]
