# Generated by Django 4.2.7 on 2026-05-27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requirement_analysis', '0002_aimodelconfig_businessrequirement_generationconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeGraphVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=20, verbose_name='版本号')),
                ('version_name', models.CharField(blank=True, max_length=100, verbose_name='版本名称')),
                ('description', models.TextField(blank=True, verbose_name='版本描述')),
                ('snapshot_data', models.JSONField(default=dict, verbose_name='快照数据')),
                ('node_count', models.PositiveIntegerField(default=0, verbose_name='实体节点数')),
                ('edge_count', models.PositiveIntegerField(default=0, verbose_name='关系边数')),
                ('document_count', models.PositiveIntegerField(default=0, verbose_name='文档数')),
                ('document_ids', models.JSONField(default=list, verbose_name='关联文档ID列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='requirement_analysis.knowledgegraph', verbose_name='关联图谱')),
            ],
            options={
                'verbose_name': '知识图谱版本',
                'verbose_name_plural': '知识图谱版本',
                'db_table': 'knowledge_graph_versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='knowledgegraphversion',
            unique_together={('graph', 'version_number')},
        ),
    ]
