# Generated by Django 4.2.7 on 2026-03-28 03:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='菜单名称')),
                ('description', models.TextField(blank=True, verbose_name='菜单描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.projectmenu', verbose_name='父菜单')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='projects.project', verbose_name='所属端')),
            ],
            options={
                'verbose_name': '端菜单',
                'verbose_name_plural': '端菜单',
                'db_table': 'project_menus',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
