# Generated by Django 4.2.7 on 2026-03-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_factory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafactoryrecord',
            name='custom_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='自定义名称'),
        ),
    ]
