# Generated by Django 4.2.7 on 2026-04-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_factory', '0004_add_bug_analysis_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugAnalysisSummaryRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='汇总分析名称')),
                ('group_by', models.CharField(default='month', help_text='week|month|quarter|half_year|year', max_length=20, verbose_name='时间聚合方式')),
                ('record_ids', models.JSONField(default=list, verbose_name='关联分析记录ID列表')),
                ('total_bugs', models.IntegerField(default=0, verbose_name='总Bug数')),
                ('total_modules', models.IntegerField(default=0, verbose_name='涉及模块数')),
                ('record_count', models.IntegerField(default=0, verbose_name='分析记录数')),
                ('online_bugs', models.IntegerField(default=0, verbose_name='线上故障数')),
                ('defect_bugs', models.IntegerField(default=0, verbose_name='缺陷数')),
                ('summary_data', models.JSONField(default=dict, help_text='包含 trends/module_ranking/risk_modules 等', verbose_name='汇总数据')),
                ('ai_insight', models.TextField(blank=True, default='', verbose_name='AI洞察报告')),
                ('created_by', models.CharField(default='system', max_length=50, verbose_name='创建者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Bug汇总分析记录',
                'verbose_name_plural': 'Bug汇总分析记录',
                'db_table': 'df_bug_analysis_summary_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='df_bug_anal_created_27c0ef_idx'), models.Index(fields=['created_by'], name='df_bug_anal_created_acdd5b_idx'), models.Index(fields=['group_by'], name='df_bug_anal_group_b_f9f87b_idx')],
            },
        ),
    ]
