# Generated by Django 4.2.30 on 2026-06-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_factory', '0006_airubricrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='buganalysisrecord',
            name='ai_progress',
            field=models.IntegerField(default=0, help_text='0-100', verbose_name='AI分析进度'),
        ),
        migrations.AddField(
            model_name='buganalysisrecord',
            name='ai_status',
            field=models.CharField(choices=[('none', '无'), ('pending', '待分析'), ('running', '分析中'), ('completed', '已完成'), ('failed', '失败')], default='none', max_length=20, verbose_name='AI分析状态'),
        ),
    ]
