# Generated by Django 4.2.30 on 2026-08-07 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_factory', '0008_merge_20260707_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugSyncItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('yunxiao_workitem_id', models.CharField(blank=True, default='', max_length=100, verbose_name='云效工作项ID')),
                ('yunxiao_serial_number', models.CharField(blank=True, default='', max_length=100, verbose_name='云效序列号')),
                ('local_data', models.JSONField(default=dict, verbose_name='本地Bug数据')),
                ('remote_data_cache', models.JSONField(blank=True, default=dict, verbose_name='云效数据缓存')),
                ('sync_status', models.CharField(choices=[('pending', '待同步'), ('synced', '已同步'), ('conflict', '冲突'), ('failed', '失败')], default='pending', max_length=20, verbose_name='同步状态')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
                ('last_remote_check_at', models.DateTimeField(blank=True, null=True, verbose_name='最后远程检查时间')),
                ('local_version_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='本地版本哈希')),
                ('remote_version_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='远程版本哈希')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('analysis_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_items', to='data_factory.buganalysisrecord', verbose_name='关联分析记录')),
            ],
            options={
                'verbose_name': 'Bug同步项',
                'verbose_name_plural': 'Bug同步项',
                'db_table': 'df_bug_sync_item',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bugsyncitem',
            index=models.Index(fields=['yunxiao_workitem_id'], name='df_bug_sync_yunxiao_944341_idx'),
        ),
        migrations.AddIndex(
            model_name='bugsyncitem',
            index=models.Index(fields=['sync_status'], name='df_bug_sync_sync_st_c3fa96_idx'),
        ),
        migrations.AddIndex(
            model_name='bugsyncitem',
            index=models.Index(fields=['analysis_record'], name='df_bug_sync_analysi_0f300c_idx'),
        ),
        migrations.AddIndex(
            model_name='bugsyncitem',
            index=models.Index(fields=['-updated_at'], name='df_bug_sync_updated_77fb57_idx'),
        ),
    ]