# Generated by Django 4.2.30 on 2026-08-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_factory', '0009_add_bug_sync_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='YunxiaoToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(default='', help_text='如: 张三-日常使用、李四-CI专用', max_length=100, verbose_name='标签/备注')),
                ('token', models.CharField(max_length=500, verbose_name='云效访问令牌(PAT)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_by', models.CharField(default='system', max_length=50, verbose_name='创建者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '云效令牌配置',
                'verbose_name_plural': '云效令牌配置',
                'db_table': 'df_yunxiao_token',
                'ordering': ['-created_at'],
            },
        ),
    ]
