# Generated by Django 4.2.7 on 2026-05-27 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0007_testcase_review_comment_testcase_review_status_and_more'),
        ('testsuites', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsuitecase',
            old_name='TestSuite',
            new_name='testsuite',
        ),
        migrations.AlterUniqueTogether(
            name='testsuitecase',
            unique_together={('testsuite', 'testcase')},
        ),
    ]
