# Generated by Django 4.2.7 on 2026-03-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='module',
            field=models.CharField(blank=True, max_length=200, verbose_name='模块'),
        ),
    ]
