# Generated by Django 4.2.7 on 2026-03-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0003_add_module_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='test_type',
            field=models.CharField(choices=[('text', '文本模式'), ('step', '步骤模式')], default='text', max_length=20, verbose_name='步骤模式'),
        ),
    ]
