# Generated by Django 4.2.7 on 2026-03-28 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectmenu'),
        ('testcases', '0004_update_step_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testcases', to='projects.projectmenu', verbose_name='所属菜单'),
        ),
    ]
