# Generated by Django 4.2.7 on 2026-03-28 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectmenu'),
        ('testcases', '0005_testcase_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testcases', to='projects.project'),
        ),
    ]
