# Generated by Django 4.2.7 on 2026-03-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiednotificationconfig',
            name='default_from_email',
            field=models.CharField(blank=True, max_length=255, verbose_name='默认发件人地址'),
        ),
        migrations.AddField(
            model_name='unifiednotificationconfig',
            name='email_host',
            field=models.CharField(blank=True, help_text='如: smtp.163.com, smtp.qq.com, smtp.gmail.com', max_length=255, verbose_name='SMTP服务器'),
        ),
        migrations.AddField(
            model_name='unifiednotificationconfig',
            name='email_host_password',
            field=models.CharField(blank=True, max_length=255, verbose_name='邮箱密码/授权码'),
        ),
        migrations.AddField(
            model_name='unifiednotificationconfig',
            name='email_host_user',
            field=models.CharField(blank=True, max_length=255, verbose_name='发件人邮箱'),
        ),
        migrations.AddField(
            model_name='unifiednotificationconfig',
            name='email_port',
            field=models.IntegerField(default=587, help_text='通常: 25, 465(SSL), 587(TLS)', verbose_name='SMTP端口'),
        ),
        migrations.AddField(
            model_name='unifiednotificationconfig',
            name='email_use_ssl',
            field=models.BooleanField(default=False, verbose_name='使用SSL'),
        ),
        migrations.AddField(
            model_name='unifiednotificationconfig',
            name='email_use_tls',
            field=models.BooleanField(default=True, verbose_name='使用TLS'),
        ),
        migrations.AlterField(
            model_name='unifiednotificationconfig',
            name='config_type',
            field=models.CharField(choices=[('webhook_feishu', '飞书机器人'), ('webhook_wechat', '企业微信机器人'), ('webhook_dingtalk', '钉钉机器人'), ('email_smtp', '邮件SMTP')], default='webhook_feishu', max_length=20, verbose_name='配置类型'),
        ),
    ]
