# Generated by Django 4.2.7 on 2026-03-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_unifiednotificationconfig_default_from_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unifiednotificationconfig',
            name='default_from_email',
        ),
        migrations.RemoveField(
            model_name='unifiednotificationconfig',
            name='email_host',
        ),
        migrations.RemoveField(
            model_name='unifiednotificationconfig',
            name='email_host_password',
        ),
        migrations.RemoveField(
            model_name='unifiednotificationconfig',
            name='email_host_user',
        ),
        migrations.RemoveField(
            model_name='unifiednotificationconfig',
            name='email_port',
        ),
        migrations.RemoveField(
            model_name='unifiednotificationconfig',
            name='email_use_ssl',
        ),
        migrations.RemoveField(
            model_name='unifiednotificationconfig',
            name='email_use_tls',
        ),
        migrations.AlterField(
            model_name='unifiednotificationconfig',
            name='config_type',
            field=models.CharField(choices=[('webhook_feishu', '飞书机器人'), ('webhook_wechat', '企业微信机器人'), ('webhook_dingtalk', '钉钉机器人')], default='webhook_feishu', max_length=20, verbose_name='配置类型'),
        ),
    ]
