# Generated by Django 4.2.30 on 2026-05-11 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='用户名只能包含字母、数字和 @/./+/-/_ ，至少2个字符', regex='^[\\w.@+-]+\\Z')], verbose_name='username'),
        ),
    ]
