# Generated by Django 4.2.7 on 2026-03-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_rename_pageindex_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasedocument',
            name='split_type',
            field=models.CharField(choices=[('semantic', '语义切分'), ('fixed', '固定长度')], default='semantic', max_length=20, verbose_name='切分方式'),
        ),
        migrations.AlterField(
            model_name='knowledgebasedocument',
            name='index_data',
            field=models.JSONField(blank=True, null=True, verbose_name='索引数据'),
        ),
        migrations.AlterField(
            model_name='knowledgebasedocument',
            name='vector_collection_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='向量索引ID'),
        ),
    ]
