# Generated by Django 4.2.7 on 2026-04-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiexecutionrecord',
            name='cli_daemon_pid',
            field=models.IntegerField(blank=True, null=True, verbose_name='守护进程PID'),
        ),
        migrations.AddField(
            model_name='aiexecutionrecord',
            name='cli_session',
            field=models.CharField(blank=True, help_text='CLI模式下使用的浏览器守护进程会话名称', max_length=100, null=True, verbose_name='CLI会话名'),
        ),
        migrations.AddField(
            model_name='aiexecutionrecord',
            name='execution_engine',
            field=models.CharField(choices=[('sdk', 'SDK模式'), ('cli', 'CLI模式')], default='sdk', help_text='SDK模式使用Python SDK调用，CLI模式使用browser-use命令行工具', max_length=20, verbose_name='执行引擎'),
        ),
        migrations.AlterField(
            model_name='aiexecutionrecord',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('passed', '成功'), ('failed', '失败'), ('stopped', '已停止')], default='pending', max_length=20, verbose_name='执行状态'),
        ),
    ]
