# Generated by Django 4.2.7 on 2026-01-25 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ui_automation", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uiproject",
            name="members",
        ),
        migrations.CreateModel(
            name="UiProjectMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "管理员"),
                            ("developer", "开发者"),
                            ("tester", "测试者"),
                            ("viewer", "观察者"),
                        ],
                        default="tester",
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="ui_automation.uiproject",
                        verbose_name="所属项目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ui_project_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI自动化项目成员",
                "verbose_name_plural": "UI自动化项目成员",
                "db_table": "ui_project_members",
                "unique_together": {("project", "user")},
            },
        ),
    ]
