# Generated by Django 4.2.7 on 2026-05-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0003_add_cli_engine_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiexecutionrecord',
            name='cli_daemon_pid',
        ),
        migrations.RemoveField(
            model_name='aiexecutionrecord',
            name='cli_session',
        ),
        migrations.RemoveField(
            model_name='aiexecutionrecord',
            name='execution_engine',
        ),
        migrations.AlterField(
            model_name='aiexecutionrecord',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('passed', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='执行状态'),
        ),
    ]
