# Generated by Django 4.2.7 on 2026-06-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0004_remove_aiexecutionrecord_cli_daemon_pid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiexecutionrecord',
            name='snapshot_data',
            field=models.JSONField(blank=True, default=dict, help_text='当前页面可交互元素的快照，格式：{"url": "...", "title": "...", "element_count": N, "elements": [...], "snapshot_text": "..."}', verbose_name='页面快照数据'),
        ),
    ]
