# Generated by Django 4.2.30 on 2026-06-21 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0005_aiexecutionrecord_snapshot_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiexecutionrecord',
            name='ai_test_suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ui_automation.aitestsuite', verbose_name='关联AI测试套件'),
        ),
    ]
